CREATE TABLE T_COMMAND (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    COMMAND TEXT NOT NULL,
    ATTEMPTS INT NOT NULL,
    IDEMPOTENCY_ID VARCHAR(36) NOT NULL,
    CONTEXT TEXT NOT NULL,

    PRIMARY KEY (ID)
);

-- https://stackoverflow.com/questions/20520443/mysql-timestamp-to-default-null-not-current-timestamp
ALTER TABLE T_COMMAND
ADD COLUMN LOCKED TIMESTAMP(3) NULL DEFAULT NULL;
